### ISSUE TITLE
Build APIs for the catalog

### ISSUE THREAD

**Issue by Phaneendra97** [Phaneendra97/fih-super-set-server#11]
https://github.com/Phaneendra97/fih-super-set-flutter/issues/5

**Comment by anoopshivayogi** [comment]
![Screenshot 2024-05-22 at 6 34 11 AM](https://github.com/Phaneendra97/fih-super-set-server/assets/15169686/3568c4b5-f3c1-47e2-b439-334c0b88a5fd)


http://localhost:4000/api/get-game-profile?game_name=op_game

**Comment by anoopshivayogi** [comment]
Finished adding catalog APIs

**Comment by anoopshivayogi** [comment]
Finished adding catalog APIs
