### ISSUE TITLE
Design DB for user profile

### ISSUE THREAD

**Issue by Phaneendra97** [Phaneendra97/fih-super-set-server#3]
Design DB for user Data, covering the entire schema as per the requirements

**Comment by Phaneendra97** [comment]
**Sample DB Design for the user profile data**

![Image](https://github.com/Phaneendra97/sih-super-set-server/assets/22639800/433638ba-5bc9-419f-a4c9-20c12c9cb5eb)

**This is open for suggestions, please drop your suggestions in this task **

**Comment by RohanL1** [comment]
Hello backend team,

Can you please add following fields in user table:
- user first name 
- user last name 
- user avatar / profile picture 
- primary language
